### ISSUE TITLE
some problem when i bash train.sh 

### ISSUE THREAD

**Issue by tsq-code** [flyinghu123/CPR#19]
hello,when i bash train.sh ,always cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'.
by the way,terminal also call me some picture can't open/read ,but i have these picture.please help me.thank you! Here are my terminal output:
~/CPR-master# bash train.sh 
2024-11-24 16:14:39.410 | INFO     | __main__:main:100 - run argv: train.py -lp log/mvtec_train --sub-categories carpet grid leather tile wood -fd ./log/foreground_mvtec_DenseNet_features.denseblock1_320/ --steps 500 -tps 50 --data-dir log/synthetic_mvtec_640_12000_True_jpg
2024-11-24 16:14:39.412 | INFO     | __main__:main:101 - args: 
{'T': 512,
 'batch_size': 32,
 'data_dir': 'log/synthetic_mvtec_640_12000_True_jpg',
 'dataset_name': 'mvtec',
 'foreground_dir': './log/foreground_mvtec_DenseNet_features.denseblock1_320/',
 'k_nearest': 10,
 'learning_rate': 0.001,
 'log_path': 'log/mvtec_train',
 'n_anomaly': 0,
 'num_workers': 8,
 'pretrained_model': 'DenseNet',
 'region_sizes': [3, 1],
 'resize': 320,
 'retrieval_dir': 'log/retrieval_mvtec_DenseNet_features.denseblock1_320',
 'scales': [4, 8],
 'steps': 500,
 'sub_categories': ['carpet', 'grid', 'leather', 'tile', 'wood'],
 'test_per_steps': 50}
INFO:timm.models._builder:Loading pretrained weights from Hugging Face hub (timm/densenet201.tv_in1k)
INFO:timm.models._hub:[timm/densenet201.tv_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
carpet train:   0%|                                                                                                                                                                     | 0/500 [00:00<?, ?it/s][ WARN:0@4.075] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\243.png'): can't open/read file: check file path/integrity
[ WARN:0@4.075] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\129.png'): can't open/read file: check file path/integrity
[ WARN:0@4.076] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\019.png'): can't open/read file: check file path/integrity
[ WARN:0@4.076] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\126.png'): can't open/read file: check file path/integrity
[ WARN:0@4.076] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\119.png'): can't open/read file: check file path/integrity
[ WARN:0@4.076] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\139.png'): can't open/read file: check file path/integrity
[ WARN:0@4.077] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\077.png'): can't open/read file: check file path/integrity
[ WARN:0@4.078] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\052.png'): can't open/read file: check file path/integrity
[ WARN:0@4.083] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\063.png'): can't open/read file: check file path/integrity                                                          
Traceback (most recent call last):
  File "/root/CPR-master/train.py", line 138, in <module>
    main(args)
  File "/root/CPR-master/train.py", line 119, in main
    batch  = [x.cuda() for x in next(dataloader_iter)]
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/CPR-master/dataset/base.py", line 200, in __getitem__
    retrieval_image = self.read_image(retrieval_image_fn, True)
  File "/root/CPR-master/dataset/base.py", line 126, in read_image
    image = read_image(fn, (self.resize, self.resize))
  File "/root/CPR-master/dataset/__init__.py", line 40, in read_image
    img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

[ WARN:0@4.084] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\147.png'): can't open/read file: check file path/integrity
[ WARN:0@4.084] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\256.png'): can't open/read file: check file path/integrity
[ WARN:0@4.085] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\236.png'): can't open/read file: check file path/integrity
[ WARN:0@4.085] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\110.png'): can't open/read file: check file path/integrity
[ WARN:0@4.086] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\249.png'): can't open/read file: check file path/integrity
[ WARN:0@4.086] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\075.png'): can't open/read file: check file path/integrity
2024-11-24 16:14:46.427 | INFO     | __main__:main:100 - run argv: train.py -lp log/mvtec_train --sub-categories bottle cable capsule hazelnut metal_nut pill screw toothbrush transistor zipper -fd ./log/foreground_mvtec_DenseNet_features.denseblock1_320/ --steps 40000 -tps 2000 --data-dir log/synthetic_mvtec_640_12000_True_jpg
2024-11-24 16:14:46.427 | INFO     | __main__:main:101 - args: 
{'T': 512,
 'batch_size': 32,
 'data_dir': 'log/synthetic_mvtec_640_12000_True_jpg',
 'dataset_name': 'mvtec',
 'foreground_dir': './log/foreground_mvtec_DenseNet_features.denseblock1_320/',
 'k_nearest': 10,
 'learning_rate': 0.001,
 'log_path': 'log/mvtec_train',
 'n_anomaly': 0,
 'num_workers': 8,
 'pretrained_model': 'DenseNet',
 'region_sizes': [3, 1],
 'resize': 320,
 'retrieval_dir': 'log/retrieval_mvtec_DenseNet_features.denseblock1_320',
 'scales': [4, 8],
 'steps': 40000,
 'sub_categories': ['bottle',
                    'cable',
                    'capsule',
                    'hazelnut',
                    'metal_nut',
                    'pill',
                    'screw',
                    'toothbrush',
                    'transistor',
                    'zipper'],
 'test_per_steps': 2000}
INFO:timm.models._builder:Loading pretrained weights from Hugging Face hub (timm/densenet201.tv_in1k)
INFO:timm.models._hub:[timm/densenet201.tv_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
bottle train:   0%|                                                                                                                                                                   | 0/40000 [00:00<?, ?it/s][ WARN:0@4.197] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\152.png'): can't open/read file: check file path/integrity
[ WARN:0@4.197] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\168.png'): can't open/read file: check file path/integrity
[ WARN:0@4.198] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\123.png'): can't open/read file: check file path/integrity
[ WARN:0@4.198] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\080.png'): can't open/read file: check file path/integrity
[ WARN:0@4.198] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\016.png'): can't open/read file: check file path/integrity
[ WARN:0@4.198] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\165.png'): can't open/read file: check file path/integrity
[ WARN:0@4.198] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\179.png'): can't open/read file: check file path/integrity
[ WARN:0@4.200] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\021.png'): can't open/read file: check file path/integrity
[ WARN:0@4.202] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\043.png'): can't open/read file: check file path/integrity                                                          
[ WARN:0@4.203] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\121.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/root/CPR-master/train.py", line 138, in <module>
    main(args)
  File "/root/CPR-master/train.py", line 119, in main
    batch  = [x.cuda() for x in next(dataloader_iter)]
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/CPR-master/dataset/base.py", line 200, in __getitem__
    retrieval_image = self.read_image(retrieval_image_fn, True)
  File "/root/CPR-master/dataset/base.py", line 126, in read_image
    image = read_image(fn, (self.resize, self.resize))
  File "/root/CPR-master/dataset/__init__.py", line 40, in read_image
    img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

[ WARN:0@4.203] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\093.png'): can't open/read file: check file path/integrity
[ WARN:0@4.203] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\047.png'): can't open/read file: check file path/integrity
[ WARN:0@4.203] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\141.png'): can't open/read file: check file path/integrity
[ WARN:0@4.203] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\126.png'): can't open/read file: check file path/integrity
[ WARN:0@4.204] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\177.png'): can't open/read file: check file path/integrity
[ WARN:0@4.204] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/bottle/train\good\000.png'): can't open/read file: check file path/integrity

**Comment by tsq-code** [comment]
[ WARN:0@4.084] global loadsave.cpp:241 findDecoder imread_('./data/mvtec/carpet/train\good\147.png'): can't open/read file: check file path/integrity
----
From this prompt you can see that there are \ and/two matches in the path, where should this be configured？

**Comment by tsq-code** [comment]
I'm sorry that I made a very stupid mistake, I mistakenly used win to generate synthetic data and then used Linux for training.
